### ISSUE TITLE
numpy dtype 的 < 应该代表小端

### ISSUE THREAD

**Issue by buMingZhen** [apachecn/apachecn-ds-zh#4]
[apachecn-ds-zh](https://github.com/apachecn/apachecn-ds-zh)/[docs](https://github.com/apachecn/apachecn-ds-zh/tree/master/docs)/[numpy-essentials](https://github.com/apachecn/apachecn-ds-zh/tree/master/docs/numpy-essentials)/4.md
"这里要注意的一件事是，我们使用了打印输出数据类型-i4和f4前面有一个<，而<代表字节顺序大端（指示内存地址增加顺序）"
< 应该代表小端
参见 https://numpy.org/doc/stable/reference/generated/numpy.dtype.newbyteorder.html

**Comment by jiangzhonglian** [comment]
如果方便提交一下 pull requests

**Comment by wizardforcel** [comment]
如果方便提交一下 pull requests
